table Retailmart_Cleaned_Dataset
	lineageTag: 3b6ebed1-4f77-48b7-92c5-48c72f8e60f7

	column 'Invoice ID'
		dataType: string
		lineageTag: bc236f65-9899-442b-9214-19bfd5dfce99
		summarizeBy: none
		sourceColumn: Invoice ID

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: 8768ee1c-8465-46f6-a9df-6968d3281f0f
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7149398d-6fd9-444b-9abd-20d08a1d2da3
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Customer type'
		dataType: string
		lineageTag: bf9730a8-c8cf-4880-a437-2c374503e2cf
		summarizeBy: none
		sourceColumn: Customer type

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: bd178dfc-3ad7-4720-81a0-898c44f02441
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Product line'
		dataType: string
		lineageTag: 8d006272-7d6f-480d-b14b-7ec91c551682
		summarizeBy: none
		sourceColumn: Product line

		annotation SummarizationSetBy = Automatic

	column 'Unit price'
		dataType: double
		lineageTag: e88e2d03-db42-4476-90bc-b50da69d2bbe
		summarizeBy: sum
		sourceColumn: Unit price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d2ce1117-cdc9-4deb-95e2-89f04e89c500
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Tax 5%'
		dataType: double
		lineageTag: c5dc4fb0-1922-45e1-95ee-7c06eecc8516
		summarizeBy: sum
		sourceColumn: Tax 5%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total
		dataType: double
		lineageTag: b515feb3-dc47-4018-8216-cd8669ed3ecf
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7fff39bd-5d2c-4665-9240-c9dd80e973ff
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 02d24212-16dc-4d20-bbe4-da1e9458604c
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Payment
		dataType: string
		lineageTag: 231183fb-bec9-4225-9cfa-af6e659f9222
		summarizeBy: none
		sourceColumn: Payment

		annotation SummarizationSetBy = Automatic

	column cogs
		dataType: double
		lineageTag: f442003e-a364-40a6-aadf-5c6413a6c4db
		summarizeBy: sum
		sourceColumn: cogs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'gross margin percentage'
		dataType: double
		lineageTag: a36fdaba-9904-4403-858c-24b6b17fffa6
		summarizeBy: sum
		sourceColumn: gross margin percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'gross income'
		dataType: double
		lineageTag: 732f36e8-502c-43c0-b8e4-07efe5b4e9ee
		summarizeBy: sum
		sourceColumn: gross income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rating
		dataType: double
		lineageTag: 975633d9-129e-44b2-a5fe-dee532c2ade6
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: string
		lineageTag: 6e7454ba-945b-4438-9b98-78decbcacfad
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Month_Number
		dataType: int64
		formatString: 0
		lineageTag: e93605e5-3e56-43fb-a951-f4db9050a66f
		summarizeBy: sum
		sourceColumn: Month_Number

		annotation SummarizationSetBy = Automatic

	partition Retailmart_Cleaned_Dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Projects\data_analytics_internship\Project_02_PowerBI_Dashboard\data\Retailmart_Cleaned_Dataset.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Invoice ID", type text}, {"Branch", type text}, {"City", type text}, {"Customer type", type text}, {"Gender", type text}, {"Product line", type text}, {"Unit price", type number}, {"Quantity", Int64.Type}, {"Tax 5%", type number}, {"Total", type number}, {"Date", type date}, {"Time", type time}, {"Payment", type text}, {"cogs", type number}, {"gross margin percentage", type number}, {"gross income", type number}, {"Rating", type number}, {"Month", type text}, {"Month_Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

